version: "3.8"

services:
    # Frontend service
    frontend:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "5173:80"
        container_name: kiosk-frontend
        restart: unless-stopped
        environment:
            - VITE_API_BASE_URL=${VITE_API_BASE_URL}
        networks:
            - kiosk-network

networks:
    kiosk-network:
        name: kiosk-network
